// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Table': string;
  'isEmpty': string;
  'isLoading': string;
}
export const cssExports: CssExports;
export default cssExports;
